markdown: kramdown

kramdown:
    input: GFM

# pygments: true
github: [Repository medata]
lsi: safe
lsi: false
source: .

title: Bagus Tris Atmaja
description: Researcher on Speech Processing

# Search configuration
search:
  enabled: true

# Enable plugins
plugins:
  - jekyll-seo-tag
